name: sudoku_suji
description: Sudoku app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:   # ⚠️ 반드시 루트 레벨 (flutter: 안 X)
  android: true
  ios: true
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/puzzles.json
    - assets/app_icon.png
    - assets/suji_kong.png
