name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PROJECT_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'   # ✅ 버전 고정
          channel: 'stable'
          cache: true

      - run: flutter --version
      - run: flutter config --enable-web
      - run: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
      - run: flutter build web --release --web-renderer html --base-href / --pwa-strategy none
        working-directory: ${{ env.PROJECT_DIR }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PROJECT_DIR }}/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
